/* eslint-disable */
/* AUTO-GENERATED by scripts/sync-published-routes.mjs — do not edit manually */

import type {TypeTagId} from '@site/src/data/insightTags';

export interface LatestInsight {
  title: string;
  date: string;
  readTime: number;
  description: string;
  typeTag: TypeTagId;
  to: string;
}

export const latestInsights: readonly LatestInsight[] = [
  {
    "title": "The Blueprint Before Training an LLM",
    "date": "2026-07-08",
    "readTime": 10,
    "description": "Hyperparameters, vocabulary, and why a 7B model is 7B before day one, how the dials connect, where parameters live, and why the context window is a budgeted choice.",
    "typeTag": "lrn",
    "to": "/insights/before-training-an-llm"
  },
  {
    "title": "Building a Unified Observability Framework",
    "date": "2026-07-07",
    "readTime": 6,
    "description": "Business, service, and infrastructure observability in large regulated enterprises. A three-layer model where every business outcome traces to system behaviour and infrastructure state.",
    "typeTag": "pov",
    "to": "/insights/unified-observability-framework"
  },
  {
    "title": "The Death of Distributed Systems? Why Agentic AI Changes the Interface, Not the Foundation",
    "date": "2026-07-07",
    "readTime": 5,
    "description": "Agentic AI does not replace distributed systems. It adds a non-deterministic reasoning layer on top of deterministic execution. Reason flexibly; execute reliably.",
    "typeTag": "pov",
    "to": "/insights/agentic-ai-distributed-systems"
  },
  {
    "title": "The First Principles of Technology",
    "date": "2026-07-06",
    "readTime": 13,
    "description": "First principles differ by decision layer. Five levels from business strategy to software engineering, and why applying the right principles at the right level matters.",
    "typeTag": "arch",
    "to": "/insights/first-principles-of-technology"
  },
  {
    "title": "Is MCP Really Necessary for Business Agents in Large Regulated Enterprises?",
    "date": "2026-07-05",
    "readTime": 10,
    "description": "MCP is a valuable standard for AI tool interoperability. For regulated business agents, the question is whether its benefits outweigh operational cost for your use case, not whether MCP is good.",
    "typeTag": "pov",
    "to": "/insights/mcp-for-enterprise-business-agents"
  },
  {
    "title": "LLM Hosting Options for Regulated Industries",
    "date": "2026-07-04",
    "readTime": 13,
    "description": "From public SaaS to air-gapped on-prem: a practical ladder of LLM hosting options, and how to choose based on regulatory pressure and engineering maturity.",
    "typeTag": "arch",
    "to": "/insights/model-hosting-options-regulated-industries"
  },
  {
    "title": "Retrieval Is a Governed Action",
    "date": "2026-07-04",
    "readTime": 12,
    "description": "Retrieval is not a database query; it is a governed action. How Policy-Governed Agent Runtime applies to RAG when context construction must be scoped, auditable, and enforced before inference.",
    "typeTag": "arch",
    "to": "/insights/retrieval-is-a-governed-action"
  },
  {
    "title": "LangChain vs LangGraph — When to Use What in Production Agents",
    "date": "2026-07-03",
    "readTime": 13,
    "description": "LangChain and LangGraph are not rivals — they are layers of the same stack. This guide explains when to use chains, agents, or graphs; pseudo-code for both paths; and how memory, validation, and LLM selection fit a governed agentic loop.",
    "typeTag": "arch",
    "to": "/insights/langchain-vs-langgraph"
  }
];
