/* eslint-disable */
/* AUTO-GENERATED by scripts/sync-published-routes.mjs — do not edit manually */

import type {TypeTagId} from '@site/src/data/insightTags';

export interface LatestInsight {
  title: string;
  date: string;
  readTime: number;
  description: string;
  typeTag: TypeTagId;
  to: string;
}

export const latestInsights: readonly LatestInsight[] = [
  {
    "title": "The Blueprint Before Training an LLM",
    "date": "2026-07-08",
    "readTime": 10,
    "description": "Hyperparameters, vocabulary, and why a 7B model is 7B before day one, how the dials connect, where parameters live, and why the context window is a budgeted choice.",
    "typeTag": "lrn",
    "to": "/insights/before-training-an-llm"
  },
  {
    "title": "The Death of Distributed Systems? Why Agentic AI Changes the Interface, Not the Foundation",
    "date": "2026-07-07",
    "readTime": 5,
    "description": "Agentic AI does not replace distributed systems. It adds a non-deterministic reasoning layer on top of deterministic execution. Reason flexibly; execute reliably.",
    "typeTag": "pov",
    "to": "/insights/agentic-ai-distributed-systems"
  },
  {
    "title": "Is MCP Really Necessary for Business Agents in Large Regulated Enterprises?",
    "date": "2026-07-05",
    "readTime": 10,
    "description": "MCP is a valuable standard for AI tool interoperability. For regulated business agents, the question is whether its benefits outweigh operational cost for your use case, not whether MCP is good.",
    "typeTag": "pov",
    "to": "/insights/mcp-for-enterprise-business-agents"
  },
  {
    "title": "Retrieval Is a Governed Action",
    "date": "2026-07-04",
    "readTime": 12,
    "description": "Retrieval is not a database query; it is a governed action. How Policy-Governed Agent Runtime applies to RAG when context construction must be scoped, auditable, and enforced before inference.",
    "typeTag": "arch",
    "to": "/insights/retrieval-is-a-governed-action"
  },
  {
    "title": "How to Design an Intent Router for Agentic AI",
    "date": "2026-07-02",
    "readTime": 12,
    "description": "A practical design guide for intent routing — route tables, layered classification, confidence thresholds, session stickiness, eval gates, and wiring dispatch into the agentic app before the model loop runs.",
    "typeTag": "arch",
    "to": "/insights/design-intent-router"
  },
  {
    "title": "What Is an Intent Router — and Why It Matters in Agentic AI",
    "date": "2026-07-02",
    "readTime": 9,
    "description": "An intent router is the first deterministic decision in an agent stack. It maps user requests to the right workflow, agent, and tool manifest before the model loop runs — and when it fails, every downstream stage can execute perfectly and still miss the user’s goal.",
    "typeTag": "arch",
    "to": "/insights/what-is-intent-router"
  },
  {
    "title": "RAG Is Not a Database",
    "date": "2026-06-27",
    "readTime": 7,
    "description": "RAG is runtime context construction at query time, not a storage layer you bolt onto an LLM.",
    "typeTag": "lrn",
    "to": "/insights/rag-is-not-a-database"
  },
  {
    "title": "Policy-Governed Agent Runtime",
    "date": "2026-06-25",
    "readTime": 16,
    "description": "Proposal is not permission. Agents propose tool calls; governance decides whether they run. An architecture breakdown of runtime trust boundaries for production agent systems in regulated industries.",
    "typeTag": "arch",
    "to": "/insights/policy-governed-agent-runtime"
  }
];
