/* eslint-disable */
/* AUTO-GENERATED by scripts/sync-published-routes.mjs — do not edit manually */

import type {TypeTagId} from '@site/src/data/insightTags';

export type InsightTabId = 'all' | 'system-design' | 'under-the-hood';

export interface LatestInsight {
  title: string;
  date: string;
  readTime: number;
  description: string;
  typeTag: TypeTagId;
  to: string;
}

export const latestInsightsByTab: Record<InsightTabId, readonly LatestInsight[]> = {
  "all": [
    {
      "title": "Spotify Music Discovery: Inverted Index Search Explained",
      "date": "2026-08-05",
      "readTime": 17,
      "description": "System design of inverted index search with a Spotify worked example: catalog vs index, title artist album lyrics postings, autocomplete, fuzzy match, ranking, and play hydration.",
      "typeTag": "arch",
      "to": "/insights/music-search-inverted-index"
    },
    {
      "title": "Spotify Music Streaming Pipeline: From Upload to Search and Play",
      "date": "2026-08-05",
      "readTime": 19,
      "description": "How a Spotify-class stack turns a master upload into searchable catalog and playable audio: ingest, multi-bitrate encode, search index, multi-CDN delivery, and client ABR over HTTP range requests.",
      "typeTag": "arch",
      "to": "/insights/spotify-music-streaming-pipeline"
    },
    {
      "title": "After Training an LLM: From Frozen Weights to Token-by-Token Inference",
      "date": "2026-07-29",
      "readTime": 11,
      "description": "What happens once training stops: frozen weights, prefill vs decode, sampling, the KV cache, and the serving tricks that make inference faster without changing what the model knows.",
      "typeTag": "exp",
      "to": "/insights/after-training-an-llm"
    },
    {
      "title": "Aligning an LLM: From Autocomplete to Assistant",
      "date": "2026-07-27",
      "readTime": 6,
      "description": "How SFT and preference tuning (RLHF/DPO) turn a pre-trained next-token model into a helpful assistant: same training loop, different data, thin layer that shapes behavior not knowledge.",
      "typeTag": "exp",
      "to": "/insights/aligning-an-llm"
    },
    {
      "title": "During Training an LLM: From Random Weights to a Working Model",
      "date": "2026-07-25",
      "readTime": 30,
      "description": "What happens inside the weight tensors as an LLM trains: random initialisation, the four-step training loop (forward, loss, backprop, optimizer), and what each component learns as a next-token model.",
      "typeTag": "exp",
      "to": "/insights/during-training-an-llm"
    },
    {
      "title": "Adaptive Video Streaming Explained: How Netflix Streams One Chunk at a Time",
      "date": "2026-07-21",
      "readTime": 9,
      "description": "Netflix does not stream one file. Chunks, quality ladders, manifests, ABR decisions, buffering, seeking, and CDN caching, one segment at a time.",
      "typeTag": "exp",
      "to": "/insights/adaptive-video-streaming-explained"
    },
    {
      "title": "Netflix Video Processing Pipeline: From Studio Upload to Global Streaming",
      "date": "2026-07-21",
      "readTime": 12,
      "description": "How Netflix turns a studio mezzanine into globally streamed ABR assets: Cosmos microservices, encoding, quality, packaging, and Open Connect delivery.",
      "typeTag": "arch",
      "to": "/insights/netflix-video-processing-pipeline"
    },
    {
      "title": "LLM Hosting Options for Regulated Industries",
      "date": "2026-07-17",
      "readTime": 13,
      "description": "From public SaaS to air-gapped on-prem: a practical ladder of LLM hosting options, and how to choose based on regulatory pressure and engineering maturity.",
      "typeTag": "arch",
      "to": "/insights/model-hosting-options-regulated-industries"
    }
  ],
  "system-design": [
    {
      "title": "Spotify Music Discovery: Inverted Index Search Explained",
      "date": "2026-08-05",
      "readTime": 17,
      "description": "System design of inverted index search with a Spotify worked example: catalog vs index, title artist album lyrics postings, autocomplete, fuzzy match, ranking, and play hydration.",
      "typeTag": "arch",
      "to": "/insights/music-search-inverted-index"
    },
    {
      "title": "Spotify Music Streaming Pipeline: From Upload to Search and Play",
      "date": "2026-08-05",
      "readTime": 19,
      "description": "How a Spotify-class stack turns a master upload into searchable catalog and playable audio: ingest, multi-bitrate encode, search index, multi-CDN delivery, and client ABR over HTTP range requests.",
      "typeTag": "arch",
      "to": "/insights/spotify-music-streaming-pipeline"
    },
    {
      "title": "Adaptive Video Streaming Explained: How Netflix Streams One Chunk at a Time",
      "date": "2026-07-21",
      "readTime": 9,
      "description": "Netflix does not stream one file. Chunks, quality ladders, manifests, ABR decisions, buffering, seeking, and CDN caching, one segment at a time.",
      "typeTag": "exp",
      "to": "/insights/adaptive-video-streaming-explained"
    },
    {
      "title": "Netflix Video Processing Pipeline: From Studio Upload to Global Streaming",
      "date": "2026-07-21",
      "readTime": 12,
      "description": "How Netflix turns a studio mezzanine into globally streamed ABR assets: Cosmos microservices, encoding, quality, packaging, and Open Connect delivery.",
      "typeTag": "arch",
      "to": "/insights/netflix-video-processing-pipeline"
    }
  ],
  "under-the-hood": [
    {
      "title": "REST vs gRPC - Under the Hood",
      "date": "2026-07-19",
      "readTime": 8,
      "description": "Resource APIs over HTTP/JSON versus function calls over HTTP/2 and protobuf. Stack placement, streaming, and when enterprises use both.",
      "typeTag": "exp",
      "to": "/insights/rest-vs-grpc-under-the-hood"
    },
    {
      "title": "HTTP/1.1 vs HTTP/2 vs HTTP/3 - Under the Hood",
      "date": "2026-07-18",
      "readTime": 9,
      "description": "One HTTP application model, three wire contracts: text + TCP, multiplexed binary on TLS/TCP, and HTTP over QUIC on UDP. Head-of-line blocking, streams, and when each wins.",
      "typeTag": "exp",
      "to": "/insights/http-1-vs-http-2-vs-http-3-under-the-hood"
    },
    {
      "title": "Load Balancer - Under the Hood",
      "date": "2026-07-18",
      "readTime": 12,
      "description": "Layer 4 vs Layer 7 load balancing: what each sees on the wire, network vs application load balancers, algorithms, health checks, and when to use which.",
      "typeTag": "exp",
      "to": "/insights/load-balancer-under-the-hood"
    },
    {
      "title": "SQL vs NoSQL - Under the Hood",
      "date": "2026-07-18",
      "readTime": 16,
      "description": "Relational tables, document stores, key-value, graph, vector, and time-series: what each model is, when to use it, when not to, and the tradeoffs under the hood.",
      "typeTag": "exp",
      "to": "/insights/sql-vs-nosql-under-the-hood"
    },
    {
      "title": "HTTPS Encryption Lifecycle - Under the Hood",
      "date": "2026-07-16",
      "readTime": 11,
      "description": "One HTTPS call from TCP open through TLS handshake, session keys, AEAD records, and teardown. Where asymmetric trust ends and symmetric bulk encryption begins.",
      "typeTag": "exp",
      "to": "/insights/https-encryption-lifecycle-under-the-hood"
    },
    {
      "title": "HTTP vs HTTPS - Under the Hood",
      "date": "2026-07-15",
      "readTime": 8,
      "description": "HTTP is the application protocol for requests and responses. HTTPS is HTTP over TLS. Methods, status, headers, the TLS wrap, certificates, and which failures people mislabel as network or app.",
      "typeTag": "exp",
      "to": "/insights/http-vs-https-under-the-hood"
    },
    {
      "title": "Symmetric vs Asymmetric Encryption - Under the Hood",
      "date": "2026-07-15",
      "readTime": 13,
      "description": "Symmetric crypto shares one secret for speed. Asymmetric uses key pairs for trust and key exchange. Where each appears in TLS, APIs, data at rest, and which mistakes look like security.",
      "typeTag": "exp",
      "to": "/insights/symmetric-vs-asymmetric-encryption-under-the-hood"
    },
    {
      "title": "CDN - Under the Hood",
      "date": "2026-07-14",
      "readTime": 11,
      "description": "A CDN is a cache-and-route fabric at the edge: PoPs, origin, cache keys, TTL, anycast, and the hit/miss path. Why delivery scales, and which failures people mislabel as app or network.",
      "typeTag": "exp",
      "to": "/insights/cdn-under-the-hood"
    }
  ]
};

// Back-compat: the curated "All" strip.
export const latestInsights: readonly LatestInsight[] = latestInsightsByTab.all;
