/* eslint-disable */
/* AUTO-GENERATED by scripts/sync-published-routes.mjs — do not edit manually */

export const publishedFrameworkSlugs: readonly string[] = [
  "gain-agents",
  "gain-aiom",
  "gain-evaluation",
  "gain-identity",
  "gain-llm",
  "gain-mcp",
  "gain-observability",
  "gain-prompt",
  "gain-rag"
];

export const publishedInsightTags = [
  "ai-intelligence",
  "governance-trust",
  "platforms-engineering",
  "system-architecture"
] as const;

export const publishedInsightTypeTags = [
  "pov",
  "arch",
  "lrn",
  "exp"
] as const;
