/* eslint-disable */
/* AUTO-GENERATED by scripts/sync-published-routes.mjs — do not edit manually */

export const publishedFrameworkSlugs: readonly string[] = [];

export const publishedDepthTags = {
  "/blueprints": [
    "ai-intelligence",
    "platforms-engineering",
    "system-architecture"
  ],
  "/architecture": [
    "platforms-engineering"
  ],
  "/playbooks": [
    "ai-intelligence",
    "platforms-engineering"
  ]
} as const;

export const publishedInsightTags = [
  "ai-intelligence",
  "governance-trust",
  "platforms-engineering",
  "system-architecture"
] as const;
